#ifndef HW_DEFS_H
#define HW_DEFS_H


/**************************************
 *	Display Definitions
 **************************************/

#define DISP_ROWS_NUM 8
#define DISP_COLS_NUM 8

#define DISP_ROWS_RCC (RCC_GPIOA | RCC_GPIOB)

#define DISP_GPIO_ROW0 GPIOA
#define DISP_GPIOP_ROW0 GPIO6

#define DISP_GPIO_ROW1 GPIOA
#define DISP_GPIOP_ROW1 GPIO7

#define DISP_GPIO_ROW2 GPIOA
#define DISP_GPIOP_ROW2 GPIO8

#define DISP_GPIO_ROW3 GPIOA
#define DISP_GPIOP_ROW3 GPIO9

#define DISP_GPIO_ROW4 GPIOA
#define DISP_GPIOP_ROW4 GPIO10

#define DISP_GPIO_ROW5 GPIOB
#define DISP_GPIOP_ROW5 GPIO0

#define DISP_GPIO_ROW6 GPIOB
#define DISP_GPIOP_ROW6 GPIO1

#define DISP_GPIO_ROW7 GPIOB
#define DISP_GPIOP_ROW7 GPIO2

#define DISP_COLS_SPI SPI1
#define DISP_COLS_GPIO_RCC (RCC_GPIOB | RCC_GPIOA)
#define DISP_COLS_SPI_RCC RCC_SPI1

#define DISP_COLS_CLK_GPIO GPIOB
#define DISP_COLS_CLK_GPIOP GPIO3
#define DISP_COLS_CLK_AF_NUM GPIO_AF0

#define DISP_COLS_DATA_GPIO GPIOB
#define DISP_COLS_DATA_GPIOP GPIO5
#define DISP_COLS_DATA_AF_NUM GPIO_AF0

#define DISP_COLS_STROBE_GPIO GPIOA
#define DISP_COLS_STROBE_GPIOP GPIO15


/**************************************
 *	USARTs Definitions
 **************************************/

#define USART_BAUDRATE 115200

#define USART_DIR_UP 2
#define USART_UP USART3
#define USART_UP_RCC RCC_USART3
#define USART_UP_IRQ NVIC_USART3_4_IRQ
#define USART_UP_RX_RCC RCC_GPIOB 
#define USART_UP_RX_PORT GPIOB 
#define USART_UP_RX_PIN GPIO11
#define USART_UP_RX_AF_NUM GPIO_AF4
#define USART_UP_TX_RCC RCC_GPIOB 
#define USART_UP_TX_PORT GPIOB 
#define USART_UP_TX_PIN GPIO10
#define USART_UP_TX_AF_NUM GPIO_AF4

#define USART_DIR_RIGHT 1
#define USART_RIGHT USART2
#define USART_RIGHT_RCC RCC_USART2
#define USART_RIGHT_IRQ NVIC_USART2_IRQ
#define USART_RIGHT_RX_RCC RCC_GPIOA 
#define USART_RIGHT_RX_PORT GPIOA 
#define USART_RIGHT_RX_PIN GPIO3
#define USART_RIGHT_RX_AF_NUM GPIO_AF1
#define USART_RIGHT_TX_RCC RCC_GPIOA
#define USART_RIGHT_TX_PORT GPIOA
#define USART_RIGHT_TX_PIN GPIO2
#define USART_RIGHT_TX_AF_NUM GPIO_AF1

#define USART_DIR_DOWN 0
#define USART_DOWN USART1
#define USART_DOWN_RCC RCC_USART1
#define USART_DOWN_IRQ NVIC_USART1_IRQ
#define USART_DOWN_RX_RCC RCC_GPIOB 
#define USART_DOWN_RX_PORT GPIOB
#define USART_DOWN_RX_PIN GPIO7
#define USART_DOWN_RX_AF_NUM GPIO_AF0
#define USART_DOWN_TX_RCC RCC_GPIOB
#define USART_DOWN_TX_PORT GPIOB
#define USART_DOWN_TX_PIN GPIO6
#define USART_DOWN_TX_AF_NUM GPIO_AF0

#define USART_DIR_LEFT 3
#define USART_LEFT USART4
#define USART_LEFT_RCC RCC_USART4
#define USART_LEFT_IRQ NVIC_USART3_4_IRQ
#define USART_LEFT_RX_RCC RCC_GPIOA 
#define USART_LEFT_RX_PORT GPIOA 
#define USART_LEFT_RX_PIN GPIO1
#define USART_LEFT_RX_AF_NUM GPIO_AF4
#define USART_LEFT_TX_RCC RCC_GPIOA
#define USART_LEFT_TX_PORT GPIOA
#define USART_LEFT_TX_PIN GPIO0
#define USART_LEFT_TX_AF_NUM GPIO_AF4

#endif
