#ifndef HW_DEFS_60X60_REV_0_2_H
#define HW_DEFS_60X60_REV_0_2_H


#ifndef HW_60x60_rev_0_2
#error The matching HW selection macro not defined
#endif

/**************************************
 *	Display Definitions
 **************************************/

#define DISP_ROWS_NUM 8
#define DISP_COLS_NUM 8

#define DISP_ROWS_RCC (RCC_GPIOA | RCC_GPIOB)

#define DISP_GPIO_ROW0 GPIOB
#define DISP_GPIOP_ROW0 GPIO7

#define DISP_GPIO_ROW1 GPIOB
#define DISP_GPIOP_ROW1 GPIO6

#define DISP_GPIO_ROW2 GPIOB
#define DISP_GPIOP_ROW2 GPIO4

#define DISP_GPIO_ROW3 GPIOB
#define DISP_GPIOP_ROW3 GPIO1

#define DISP_GPIO_ROW4 GPIOB
#define DISP_GPIOP_ROW4 GPIO0

#define DISP_GPIO_ROW5 GPIOA
#define DISP_GPIOP_ROW5 GPIO8

#define DISP_GPIO_ROW6 GPIOA
#define DISP_GPIOP_ROW6 GPIO7

#define DISP_GPIO_ROW7 GPIOA
#define DISP_GPIOP_ROW7 GPIO6


#define DISP_COLS_SPI SPI1
#define DISP_COLS_GPIO_RCC (RCC_GPIOB | RCC_GPIOA)
#define DISP_COLS_SPI_RCC RCC_SPI1

#define DISP_COLS_CLK_GPIO GPIOB
#define DISP_COLS_CLK_GPIOP GPIO3
#define DISP_COLS_CLK_AF_NUM GPIO_AF0

#define DISP_COLS_DATA_GPIO GPIOB
#define DISP_COLS_DATA_GPIOP GPIO5
#define DISP_COLS_DATA_AF_NUM GPIO_AF0

#define DISP_COLS_STROBE_GPIO GPIOA
#define DISP_COLS_STROBE_GPIOP GPIO15

#define DISP_COLS_DATA_BACKWARDS


/**************************************
 *	USARTs Definitions
 **************************************/

#define USART_BAUDRATE 115200

/*
 * need to be the uart number - 1 because it is used as 
 * index to the buffer array
 */
#define USART_DIR_UP 3
#define USART_DIR_DOWN 1
#define USART_DIR_LEFT 2
#define USART_DIR_RIGHT 0

#define USART_UP USART4
#define USART_UP_RCC RCC_USART4
#define USART_UP_IRQ NVIC_USART3_4_IRQ
#define USART_UP_RX_RCC RCC_GPIOA 
#define USART_UP_RX_PORT GPIOA 
#define USART_UP_RX_PIN GPIO1
#define USART_UP_RX_AF_NUM GPIO_AF4
#define USART_UP_TX_RCC RCC_GPIOA
#define USART_UP_TX_PORT GPIOA
#define USART_UP_TX_PIN GPIO0
#define USART_UP_TX_AF_NUM GPIO_AF4

#define USART_DOWN USART2
#define USART_DOWN_RCC RCC_USART2
#define USART_DOWN_IRQ NVIC_USART2_IRQ
#define USART_DOWN_RX_RCC RCC_GPIOA 
#define USART_DOWN_RX_PORT GPIOA 
#define USART_DOWN_RX_PIN GPIO3
#define USART_DOWN_RX_AF_NUM GPIO_AF1
#define USART_DOWN_TX_RCC RCC_GPIOA
#define USART_DOWN_TX_PORT GPIOA
#define USART_DOWN_TX_PIN GPIO2
#define USART_DOWN_TX_AF_NUM GPIO_AF1

#define USART_LEFT USART3
#define USART_LEFT_RCC RCC_USART3
#define USART_LEFT_IRQ NVIC_USART3_4_IRQ
#define USART_LEFT_RX_RCC RCC_GPIOB 
#define USART_LEFT_RX_PORT GPIOB 
#define USART_LEFT_RX_PIN GPIO11
#define USART_LEFT_RX_AF_NUM GPIO_AF4
#define USART_LEFT_TX_RCC RCC_GPIOB 
#define USART_LEFT_TX_PORT GPIOB 
#define USART_LEFT_TX_PIN GPIO10
#define USART_LEFT_TX_AF_NUM GPIO_AF4

#define USART_RIGHT USART1
#define USART_RIGHT_RCC RCC_USART1
#define USART_RIGHT_IRQ NVIC_USART1_IRQ
#define USART_RIGHT_RX_RCC RCC_GPIOA 
#define USART_RIGHT_RX_PORT GPIOA
#define USART_RIGHT_RX_PIN GPIO10
#define USART_RIGHT_RX_AF_NUM GPIO_AF1
#define USART_RIGHT_TX_RCC RCC_GPIOA
#define USART_RIGHT_TX_PORT GPIOA
#define USART_RIGHT_TX_PIN GPIO9
#define USART_RIGHT_TX_AF_NUM GPIO_AF1

#endif
