#ifndef USART_BUFFERED_H
#define USART_BUFFERED_H

#include <libopencm3/stm32/usart.h>


#define USART_TX1_BUF_SZ 16
#define USART_TX2_BUF_SZ 16
#define USART_TX3_BUF_SZ 16
#define USART_TX4_BUF_SZ 16

#define USART_RX1_BUF_SZ 16
#define USART_RX2_BUF_SZ 16
#define USART_RX3_BUF_SZ 16
#define USART_RX4_BUF_SZ 16



//#define USART_BAUDRATE 38400
#define USART_BAUDRATE 115200

#define NORTH 2
#define USART_NORTH USART3
#define USART_NORTH_RCC RCC_USART3
#define USART_NORTH_IRQ NVIC_USART3_4_IRQ
#define USART_NORTH_RX_RCC RCC_GPIOB 
#define USART_NORTH_RX_PORT GPIOB 
#define USART_NORTH_RX_PIN GPIO11
#define USART_NORTH_RX_AF_NUM GPIO_AF4
#define USART_NORTH_TX_RCC RCC_GPIOB 
#define USART_NORTH_TX_PORT GPIOB 
#define USART_NORTH_TX_PIN GPIO10
#define USART_NORTH_TX_AF_NUM GPIO_AF4


#define EAST 1
#define USART_EAST USART2
#define USART_EAST_RCC RCC_USART2
#define USART_EAST_IRQ NVIC_USART2_IRQ
#define USART_EAST_RX_RCC RCC_GPIOA 
#define USART_EAST_RX_PORT GPIOA 
#define USART_EAST_RX_PIN GPIO3
#define USART_EAST_RX_AF_NUM GPIO_AF1
#define USART_EAST_TX_RCC RCC_GPIOA
#define USART_EAST_TX_PORT GPIOA
#define USART_EAST_TX_PIN GPIO2
#define USART_EAST_TX_AF_NUM GPIO_AF1



#define SOUTH 0
#define USART_SOUTH USART1
#define USART_SOUTH_RCC RCC_USART1
#define USART_SOUTH_IRQ NVIC_USART1_IRQ
#define USART_SOUTH_RX_RCC RCC_GPIOB 
#define USART_SOUTH_RX_PORT GPIOB
#define USART_SOUTH_RX_PIN GPIO7
#define USART_SOUTH_RX_AF_NUM GPIO_AF0
#define USART_SOUTH_TX_RCC RCC_GPIOB
#define USART_SOUTH_TX_PORT GPIOB
#define USART_SOUTH_TX_PIN GPIO6
#define USART_SOUTH_TX_AF_NUM GPIO_AF0



#define WEST 3
#define USART_WEST USART4
#define USART_WEST_RCC RCC_USART4
#define USART_WEST_IRQ NVIC_USART3_4_IRQ
#define USART_WEST_RX_RCC RCC_GPIOA 
#define USART_WEST_RX_PORT GPIOA 
#define USART_WEST_RX_PIN GPIO1
#define USART_WEST_RX_AF_NUM GPIO_AF4
#define USART_WEST_TX_RCC RCC_GPIOA
#define USART_WEST_TX_PORT GPIOA
#define USART_WEST_TX_PIN GPIO0
#define USART_WEST_TX_AF_NUM GPIO_AF4

void send_char(uint8_t u, uint8_t c);
uint32_t get_char(uint8_t u);
void usart_init(void);

#endif
