%.bin:%.elf
	@echo 'Creating a binary ($@) from the .elf ($@) file. . . .'
	arm-none-eabi-objcopy -O binary "$<" "$@"
	@echo ' '

prg: $(BINARY).bin
	@echo programming...
	openocd -f ../openocd_stm32_orange.cfg -c"init" -c"reset halt" -c"flash write_image erase $(BINARY).bin 0x8000000" -c"reset" -c"exit"

