%.bin:%.elf
	@echo 'Creating a binary ($@) from the .elf ($@) file. . . .'
	arm-none-eabi-objcopy -O binary "$<" "$@"
	@echo ' '

prg: $(BINARY).bin
	@echo programming...
	openocd -f ../openocd_stm32_orange.cfg -c"program $(BINARY).elf verify reset exit"

# FIXME what is the meaning of the number behind colon?
prg_usb: $(BINARY).bin
	@sudo dfu-util -a 0 -D $(BINARY).bin -s 0x08000000:131072
